//
//  File.swift
//  
//
//  Created by Leo Dion on 6/9/23.
//

import Foundation

let taskNames = 
["Bushel WWDC",
"Prepare for WWDC Questions, Clear Talks",
"EAS - WWDC SN",
"EAS - WWDC TP",
"EAS - Tuist Pedro TP",
"EAS - Hidde watchOS 10 TP",
"EAS - Adrian TP",
"Pragma Conference CFP/Swift Connection",
"FloxBx Issues",
"StealthyStash",
"gBeat/HW - Workout Fix",
"Fix Lawnmower",
"Gitlab Funding",
"Clean Room",
"Basketball Hoop",
"Soccer Goals",
"Clean Garage",
"Dad’s Books",
"Fix Backyard Patio",
"Joannis - OAuth",
"Fuzzing ThirtyTo",
"Delta Township Calendar",
"Laptop Luggage",
"EAS - Tuist Pedro SN",
"EAS - Hidde watchOS 10 SN",
"EAS - Adrian SN",
"Social Media",
"LinkedIn Recommendations",
"Personal Finance",
"Andrew - Android",
"Amanda - React",
"Polywork",
"Cross Post Audit",
"Dev.To",
"Ahmed - BD Issues v4",
"AppFigures Thing",
"Research HeartRate & Pulsoid",
"Brightdigit membership",
"Video - Building a Web Site in Swift - Recording",
"BD - Web - v4 Issues",
"Migrate Personal Website",
"Student Handbook",
"Door Bell",
"Podcast Guests",
"Clean Workbench",
"Backend Cheat Sheet",
"Podcast Sponsors",
"Heartwitch - website update",
"MistKit Public DB",
"MistKit 0.2.4",
"SwiftTube - README - 0.2.0",
"SwiftTube + NativeYoutube",
"Photo VR",
"SwiftTube - DocC",
"Canary - README - 0.2.0",
"Family Assistant",
"Heartwitch - Workout Option",
"Orchardnest - Monitoring",
"Orchardnest - Reporting and Analytics",
"Orchardnest v0.5.0",
"Q4 Taxes",
"Q3 + Property Taxes",
"Heartwitch Meeting",
"Sofia Confirmation Info",
"PassKey",
"Migrate Objective c Article",
"Kill Mice",
"Audible",
"Sheekly Migration",
"Cleaning Toaster Oven",
"Swift Package Registry",
"Work on RiP",
"Work on Ardino",
"Credit Freeze Kids",
"DetectableSubject",
"Video - Shareplay - Recording",
"Video - Doing More with Server-Side Swift",
"Email",
"Fix Sappi For AS",
"Heartwitch - RevenueCat",
"Heartwitch - SEO Marketing Tips",
"Heartwitch - Support",
"Manage Contacts",
"Music Library Audit",
"SPM Article #3 - CI",
"Update Vapor 4 tutorial",
"Video - Continuous Integration - Automating All The Things!",
"gBeat Documentation"]
