name: DoerDay
options:
  bundleIdPrefix: com.brightdigit
  deploymentTarget:
    watchOS: 10.0
    iOS: 17.0
    macOS: 14.0
settings:
  DEVELOPMENT_TEAM: MLT7M394S7
  CODE_SIGN_IDENTITY: "Apple Development"
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"
  bundleIdPrefix: com.brightdigit
  PRODUCT_NAME: DoerDay
  LINT_MODE: ${LINT_MODE}
packages:
  DoerDayApp:
    path: ./Packages/DoerDayKit
targets:
  DoerDay.watchkitapp:
    type: application
    platform: watchOS
    scheme: {}
    dependencies:
      - package: DoerDayApp
    sources:
      - path: "Support/watchOS"
        name: watchOS
        group: Support
      - path: "Shared"
    info:
      path: Support/watchOS/Info.plist
      properties:
        WKWatchKitApp: true
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleDisplayName: DoerDay
        WKCompanionAppBundleIdentifier: com.brightdigit.DoerDay
    entitlements:
      path: Support/watchOS/watchOS.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.brightdigit.DoerDay
    settings:
      configs:
        Debug:
          CODE_SIGN_IDENTITY: iPhone Developer
          PROVISIONING_PROFILE_SPECIFIER: match Development com.brightdigit.DoerDay.watchkitapp
        Release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: match AppStore com.brightdigit.DoerDay.watchkitapp
  DoerDay.iOS:
    type: application
    platform: iOS
    scheme: {}
    dependencies:
      - package: DoerDayApp
      #- target: "DoerDay.watchkitapp"
    sources:
      - path: "Support/iOS"
        name: iOS
        group: Support
      - path: "Shared"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ${bundleIdPrefix}.DoerDay
      configs:
        Debug:
          CODE_SIGN_IDENTITY: iPhone Developer
          PROVISIONING_PROFILE_SPECIFIER: match Development com.brightdigit.DoerDay
        Release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: match AppStore com.brightdigit.DoerDay
    info:
      path: Support/iOS/Info.plist
      properties:
        ITSAppUsesNonExemptEncryption: false
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleDisplayName: DoerDay
        UILaunchStoryboardName: Launch Screen.storyboard
    entitlements:
      path: Support/iOS/iOS.entitlements
      properties:
        com.apple.developer.applesignin: 
          - Default
        aps-environment: development
        #aps-environment: development
        #com.apple.developer.siri: true
        com.apple.security.files.user-selected.read-only: true
        com.apple.security.application-groups:
          - group.com.brightdigit.DoerDay
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.brightdigit.DoerDay
    postBuildScripts:
    - path: Packages/DoerDayKit/scripts/lint.sh
      name: Lint
      basedOnDependencyAnalysis: false  
  DoerDay.macOS:
    type: application
    platform: macOS
    scheme: {}
    dependencies:
      - package: DoerDayApp
    info:
      path: Support/macOS/Info.plist
      properties:
        ITSAppUsesNonExemptEncryption: false
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleDisplayName: DoerDay
    sources:
      - path: "Support/macOS"
        name: macOS
        group: Support
      - path: "Shared"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ${bundleIdPrefix}.DoerDay
      configs:
        Debug:
          CODE_SIGN_IDENTITY: iPhone Developer
          PROVISIONING_PROFILE_SPECIFIER: match Development com.brightdigit.DoerDay macos
        Release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: match AppStore com.brightdigit.DoerDay macos
      path: Support/macOS/Info.plist
      properties:
        ITSAppUsesNonExemptEncryption: false
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleDisplayName: DoerDay
    entitlements:
      path: Support/macOS/macOS.entitlements
      properties:
        com.apple.developer.applesignin: 
          - Default
        #aps-environment: development
        #com.apple.developer.siri: true
        com.apple.security.network.client: true
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-only: true
        com.apple.security.application-groups:
          - group.com.brightdigit.DoerDay
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.brightdigit.DoerDay
    postBuildScripts:
    - path: Packages/DoerDayKit/scripts/lint.sh
      name: Lint
      basedOnDependencyAnalysis: false  